# Generated by Django 3.2.2 on 2021-05-10 19:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chinese_characters', models.CharField(max_length=10)),
                ('pinyin', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=50)),
                ('definition', models.CharField(blank=True, max_length=100)),
                ('hsk_level', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
            ],
        ),
        migrations.CreateModel(
            name='HSKLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('words', models.ManyToManyField(blank=True, to='hsk_server.Word')),
            ],
        ),
    ]
