# Generated by Django 3.2.2 on 2021-05-10 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hsk_server', '0003_rename_words_revisionword_revision_word'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RevisionWord',
        ),
    ]
