# Generated by Django 3.2.2 on 2021-05-10 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsk_server', '0004_delete_revisionword'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='revise',
            field=models.BooleanField(default=False),
        ),
    ]
