# Generated by Django 3.1.1 on 2020-09-09 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsk_framework', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hsk1',
            name='pingyin',
            field=models.CharField(max_length=20),
        ),
    ]
