# Generated by Django 3.1.1 on 2020-09-11 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsk_framework', '0002_auto_20200909_2025'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HSK1',
            new_name='Word',
        ),
        migrations.CreateModel(
            name='HSK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.ManyToManyField(to='hsk_framework.Word')),
            ],
        ),
    ]
